jwt:
    access-secret: ${JWT_ACCESS_SECRET}
    access-expiry-ms: 900000            # 15 minutes
    refresh-expiry-ms: 604800000        # 7 days

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org.springframework.security: DEBUG
app:
  base-url: ${APP_BASE_URL:http://localhost:8080}